FROM python:latest

COPY . /home/AiProjectFlask

WORKDIR /home/AiProjectFlask

RUN apt-get upgrade -y \
	&& pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple \
	&& pip install gevent gunicorn

EXPOSE 8193

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8193", "app:app"]
